version: '2'
services:
  master:
    image: spark:1.6.1
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.master.Master -h master
    hostname: master
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_MASTER_IP: master
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040
      - 6066
      - 7077
      - 8080
    #volumes:
    #  - ./conf/master:/conf
    networks:
      - spark-clstr-dev

  worker:
    image: spark:1.6.1
    command: /usr/local/spark/bin/spark-class org.apache.spark.deploy.worker.Worker -c 2 -m 4gb spark://master:7077
    hostname: worker
    environment:
      SPARK_CONF_DIR: /conf
    links:
      - master
    expose:
      - 8081
    #volumes:
    #  - ./conf/worker:/conf
    networks:
      - spark-clstr-dev

  spark-ui-proxy:
    image: yanndegat/spark-ui-proxy
    command: master:8080 9999
    ports:
      - 9999
    networks:
      - spark-clstr-dev

  jupyter:
    image: jupyter-spark:1.6.1
    ports:
      - 8888
    networks:
      - spark-clstr-dev
    environment:
      - SPARK_OPTS=--master spark://master:7077 --executor-memory 3gb --properties-file ~/work/spark-properties.conf

networks:
  spark-clstr-dev:
